.PHONY: clean All

All:
	@echo "----------Building project:[ test02 - Debug ]----------"
	@cd "D:\Projects\test02" && $(MAKE) -f  "test02.mk"
clean:
	@echo "----------Cleaning project:[ test02 - Debug ]----------"
	@cd "D:\Projects\test02" && $(MAKE) -f  "test02.mk" clean
