//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/notebook.h>
#include <wx/imaglist.h>
#include <wx/grid.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#include <wx/statusbr.h>
#include <wx/timer.h>
#include "my_defines.h"

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxNotebook* m_notebook23;
    wxPanel* m_panel35;
    wxPanel* m_panel99;
    wxGrid* m_grid53;
    wxPanel* m_panel61;
    wxButton* m_button67;
    wxButton* m_button69;
    wxButton* m_button71;
    wxButton* m_button73;
    wxButton* m_button289;
    wxButton* m_button75;
    wxButton* m_button174;
    wxPanel* m_panel37;
    wxButton* m_button47;
    wxPanel* m_panel39;
    wxButton* m_button51;
    wxNotebook* m_notebook220;
    wxPanel* m_panel224;
    wxPanel* m_panel204;
    wxTextCtrl* m_textCtrl91;
    wxTextCtrl* m_textCtrl93;
    wxTextCtrl* m_textCtrl95;
    wxPanel* m_panel226;
    wxTextCtrl* m_textCtrl238;
    wxPanel* m_panel248;
    wxButton* m_button242;
    wxButton* m_button244;
    wxButton* m_button246;
    wxPanel* m_panel228;
    wxButton* m_button236;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem9;
    wxToolBar* m_mainToolbar;
    wxStatusBar* m_statusBar11;
    wxTimer* m_timer142;

protected:
    virtual void edit_distinta(wxGridEvent& event) { event.Skip(); }
    virtual void comando_distinta(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void comando_toolbar(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTimer(wxTimerEvent& event) { event.Skip(); }

public:
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
