//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"
#include "my_defines.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer1 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer1);
    
    m_mainPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer1->Add(m_mainPanel, 1, wxEXPAND, 5);
    
    wxBoxSizer* boxSizer13 = new wxBoxSizer(wxVERTICAL);
    m_mainPanel->SetSizer(boxSizer13);
    
    m_notebook23 = new wxNotebook(m_mainPanel, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxBK_DEFAULT);
    
    boxSizer13->Add(m_notebook23, 1, wxALL|wxEXPAND|wxALIGN_TOP, 5);
    
    m_panel35 = new wxPanel(m_notebook23, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook23->AddPage(m_panel35, _("Distinta"), false);
    
    wxBoxSizer* boxSizer41 = new wxBoxSizer(wxHORIZONTAL);
    m_panel35->SetSizer(boxSizer41);
    
    m_panel99 = new wxPanel(m_panel35, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer41->Add(m_panel99, 1, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer111 = new wxBoxSizer(wxVERTICAL);
    m_panel99->SetSizer(boxSizer111);
    
    m_grid53 = new wxGrid(m_panel99, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxWANTS_CHARS);
    m_grid53->CreateGrid(0, 0);
    m_grid53->SetRowLabelAlignment(wxALIGN_RIGHT, wxALIGN_CENTRE);
    m_grid53->SetColLabelAlignment(wxALIGN_CENTRE, wxALIGN_CENTRE);
    #if wxVERSION_NUMBER >= 2904
    m_grid53->UseNativeColHeader(true);
    #endif
    m_grid53->EnableEditing(true);
    
    boxSizer111->Add(m_grid53, 1, wxALL|wxEXPAND, 5);
    
    m_panel61 = new wxPanel(m_panel35, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer41->Add(m_panel61, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer65 = new wxBoxSizer(wxVERTICAL);
    m_panel61->SetSizer(boxSizer65);
    
    m_button67 = new wxButton(m_panel61, ID_INSRDIS, _("Ins"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_button67->SetToolTip(_("Inserisce riga"));
    
    boxSizer65->Add(m_button67, 0, wxALL, 5);
    
    m_button69 = new wxButton(m_panel61, ID_DELRDIS, _("Del"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button69, 0, wxALL, 5);
    
    m_button71 = new wxButton(m_panel61, ID_COPRDIS, _("Copy"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button71, 0, wxALL, 5);
    
    m_button73 = new wxButton(m_panel61, ID_SAVEDIS, _("Save"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button73, 0, wxALL, 5);
    
    m_button289 = new wxButton(m_panel61, ID_SAVADIS, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button289, 0, wxALL, 5);
    
    m_button75 = new wxButton(m_panel61, ID_LOADDIS, _("Load"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button75, 0, wxALL, 5);
    
    m_button174 = new wxButton(m_panel61, ID_VUOTDIS, _("Reset"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer65->Add(m_button174, 0, wxALL, 5);
    
    m_panel37 = new wxPanel(m_notebook23, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook23->AddPage(m_panel37, _("Page"), false);
    
    wxBoxSizer* boxSizer45 = new wxBoxSizer(wxVERTICAL);
    m_panel37->SetSizer(boxSizer45);
    
    m_button47 = new wxButton(m_panel37, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer45->Add(m_button47, 0, wxALL, 5);
    
    m_panel39 = new wxPanel(m_notebook23, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook23->AddPage(m_panel39, _("Page"), false);
    
    wxBoxSizer* boxSizer49 = new wxBoxSizer(wxVERTICAL);
    m_panel39->SetSizer(boxSizer49);
    
    m_button51 = new wxButton(m_panel39, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer49->Add(m_button51, 0, wxALL, 5);
    
    m_notebook220 = new wxNotebook(m_mainPanel, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxBK_BOTTOM);
    
    boxSizer13->Add(m_notebook220, 0, wxALL|wxEXPAND, 5);
    
    m_panel224 = new wxPanel(m_notebook220, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook220->AddPage(m_panel224, _("Page"), false);
    
    wxBoxSizer* boxSizer200 = new wxBoxSizer(wxHORIZONTAL);
    m_panel224->SetSizer(boxSizer200);
    
    m_panel204 = new wxPanel(m_panel224, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_panel204->SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    
    boxSizer200->Add(m_panel204, 1, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer89 = new wxBoxSizer(wxVERTICAL);
    m_panel204->SetSizer(boxSizer89);
    
    m_textCtrl91 = new wxTextCtrl(m_panel204, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY);
    m_textCtrl91->SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    m_textCtrl91->SetForegroundColour(wxColour(wxT("rgb(0,255,255)")));
    
    boxSizer89->Add(m_textCtrl91, 0, wxALL|wxEXPAND, 5);
    
    m_textCtrl93 = new wxTextCtrl(m_panel204, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY);
    
    boxSizer89->Add(m_textCtrl93, 0, wxALL|wxEXPAND, 5);
    
    m_textCtrl95 = new wxTextCtrl(m_panel204, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY);
    
    boxSizer89->Add(m_textCtrl95, 0, wxALL|wxEXPAND, 5);
    
    m_panel226 = new wxPanel(m_notebook220, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook220->AddPage(m_panel226, _("Page"), false);
    
    wxBoxSizer* boxSizer230 = new wxBoxSizer(wxHORIZONTAL);
    m_panel226->SetSizer(boxSizer230);
    
    m_textCtrl238 = new wxTextCtrl(m_panel226, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_MULTILINE);
    m_textCtrl238->SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    m_textCtrl238->SetForegroundColour(wxColour(wxT("rgb(0,255,64)")));
    wxFont m_textCtrl238Font(8, wxFONTFAMILY_DEFAULT, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_NORMAL, false, wxT("Tahoma"));
    m_textCtrl238->SetFont(m_textCtrl238Font);
    
    boxSizer230->Add(m_textCtrl238, 1, wxALL|wxEXPAND, 5);
    
    m_panel248 = new wxPanel(m_panel226, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    
    boxSizer230->Add(m_panel248, 0, wxALL, 5);
    
    wxBoxSizer* boxSizer240 = new wxBoxSizer(wxVERTICAL);
    m_panel248->SetSizer(boxSizer240);
    
    m_button242 = new wxButton(m_panel248, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer240->Add(m_button242, 0, wxALL, 5);
    
    m_button244 = new wxButton(m_panel248, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer240->Add(m_button244, 0, wxALL, 5);
    
    m_button246 = new wxButton(m_panel248, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer240->Add(m_button246, 0, wxALL, 5);
    
    m_panel228 = new wxPanel(m_notebook220, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxTAB_TRAVERSAL);
    m_notebook220->AddPage(m_panel228, _("Page"), false);
    
    wxBoxSizer* boxSizer234 = new wxBoxSizer(wxVERTICAL);
    m_panel228->SetSizer(boxSizer234);
    
    m_button236 = new wxButton(m_panel228, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer234->Add(m_button236, 0, wxALL, 5);
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_name6 = new wxMenu();
    m_menuBar->Append(m_name6, _("File"));
    
    m_menuItem7 = new wxMenuItem(m_name6, wxID_EXIT, _("Exit\tAlt-X"), _("Quit"), wxITEM_NORMAL);
    m_name6->Append(m_menuItem7);
    
    m_name8 = new wxMenu();
    m_menuBar->Append(m_name8, _("Help"));
    
    m_menuItem9 = new wxMenuItem(m_name8, wxID_ABOUT, _("About..."), wxT(""), wxITEM_NORMAL);
    m_name8->Append(m_menuItem9);
    
    m_mainToolbar = this->CreateToolBar(wxTB_TEXT, wxID_ANY);
    m_mainToolbar->SetToolBitmapSize(wxSize(64,64));
    
    m_mainToolbar->AddSeparator();
    
    m_mainToolbar->AddTool(wxID_ANY, _("Tool Label"), wxXmlResource::Get()->LoadBitmap(wxT("fup_blue")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    m_mainToolbar->Realize();
    
    m_statusBar11 = new wxStatusBar(this, wxID_ANY, wxST_SIZEGRIP);
    m_statusBar11->SetFieldsCount(4);
    this->SetStatusBar(m_statusBar11);
    
    m_timer142 = new wxTimer;
    
    SetSizeHints(800,600);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
    // Connect events
    m_grid53->Connect(wxEVT_GRID_CELL_CHANGE, wxGridEventHandler(MainFrameBaseClass::edit_distinta), NULL, this);
    m_button67->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button69->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button71->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button73->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button289->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button75->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button174->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    this->Connect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Connect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Connect(wxID_ANY, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_toolbar), NULL, this);
    m_timer142->Connect(wxEVT_TIMER, wxTimerEventHandler(MainFrameBaseClass::OnTimer), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    m_grid53->Disconnect(wxEVT_GRID_CELL_CHANGE, wxGridEventHandler(MainFrameBaseClass::edit_distinta), NULL, this);
    m_button67->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button69->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button71->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button73->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button289->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button75->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    m_button174->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_distinta), NULL, this);
    this->Disconnect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Disconnect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Disconnect(wxID_ANY, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::comando_toolbar), NULL, this);
    m_timer142->Disconnect(wxEVT_TIMER, wxTimerEventHandler(MainFrameBaseClass::OnTimer), NULL, this);
    
    m_timer142->Stop();
    wxDELETE( m_timer142 );

}
